defmodule Twitter.Repo.Migrations.AddTweetVectors1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:tweets, ["full_text_vector vector_cosine_ops"],
             name: "tweets_full_text_vector_index",
             concurrently: true,
             using: "hnsw"
           )
  end

  def down do
    drop_if_exists index(:tweets, ["full_text_vector vector_cosine_ops"],
                     name: "tweets_full_text_vector_index"
                   )
  end
end
