defmodule Twitter.Repo.Migrations.AddUserToTweetsAndLikes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tweets) do
      add :user_id,
          references(:users,
            column: :id,
            name: "tweets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:likes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tweet_id,
          references(:tweets,
            column: :id,
            name: "likes_tweet_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "likes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:likes, "likes_tweet_id_fkey")

    drop constraint(:likes, "likes_user_id_fkey")

    drop table(:likes)

    drop constraint(:tweets, "tweets_user_id_fkey")

    alter table(:tweets) do
      remove :user_id
    end
  end
end
