defmodule Twitter.Repo.Migrations.AddOauth2Server do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:oauth_refresh_tokens, primary_key: false) do
      add :token_hash, :text, null: false
      add :client_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :scope, :text, null: false
      add :resource_uri, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :chain_id, :uuid, null: false
      add :rotated_to_id, :uuid
      add :rotated_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :generation, :bigint, null: false, default: 0
    end

    create unique_index(:oauth_refresh_tokens, [:token_hash],
             name: "oauth_refresh_tokens_by_token_hash_index"
           )

    create table(:oauth_consents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :user_id, :uuid, null: false
      add :client_id, :uuid, null: false
      add :scope, :text, null: false
      add :granted_at, :utc_datetime_usec, null: false
    end

    create unique_index(:oauth_consents, [:user_id, :client_id],
             name: "oauth_consents_by_user_client_index"
           )

    create table(:oauth_clients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :client_name, :text, null: false
      add :redirect_uris, {:array, :text}, null: false
      add :grant_types, {:array, :text}
      add :response_types, {:array, :text}
      add :token_endpoint_auth_method, :text
      add :scope, :text
      add :cimd_url, :text
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:oauth_clients, [:cimd_url], name: "oauth_clients_by_cimd_url_index")

    create table(:oauth_authorization_codes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :client_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :redirect_uri, :text, null: false
      add :code_challenge, :text, null: false
      add :scope, :text, null: false
      add :resource_uri, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :consumed_at, :utc_datetime_usec
    end
  end

  def down do
    drop table(:oauth_authorization_codes)

    drop_if_exists unique_index(:oauth_clients, [:cimd_url],
                     name: "oauth_clients_by_cimd_url_index"
                   )

    drop table(:oauth_clients)

    drop_if_exists unique_index(:oauth_consents, [:user_id, :client_id],
                     name: "oauth_consents_by_user_client_index"
                   )

    drop table(:oauth_consents)

    drop_if_exists unique_index(:oauth_refresh_tokens, [:token_hash],
                     name: "oauth_refresh_tokens_by_token_hash_index"
                   )

    drop table(:oauth_refresh_tokens)
  end
end
