defmodule Twitter.Repo.Migrations.AddIdentityReferencesAndLikeIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:likes, "likes_tweet_id_fkey")

    create unique_index(:likes, [:user_id, :tweet_id], name: "likes_unique_user_tweet_index")

    alter table(:likes) do
      modify :tweet_id,
             references(:tweets,
               column: :id,
               name: "likes_tweet_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:likes, [:tweet_id])
  end

  def down do
    drop_if_exists index(:likes, [:tweet_id])

    drop constraint(:likes, "likes_tweet_id_fkey")

    alter table(:likes) do
      modify :tweet_id,
             references(:tweets,
               column: :id,
               name: "likes_tweet_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop_if_exists unique_index(:likes, [:user_id, :tweet_id],
                     name: "likes_unique_user_tweet_index"
                   )
  end
end
